require 'json'

# Use Node.js to resolve the path of `react_native_pods.rb`
react_native_pods_rb_path = Pod::Executable.execute_command(
  'node', ['-p',
  'require.resolve("react-native/scripts/react_native_pods.rb", { paths: [process.argv[1]] })', __dir__]
).strip

require react_native_pods_rb_path

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Set up Flipper configuration based on environment variable
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# Linkage type (static or dynamic frameworks)
linkage = ENV['USE_FRAMEWORKS']
if linkage
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Elewa' do
  config = use_native_modules!

  # Get default flags (e.g., Hermes, Fabric)
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is enabled by default in React Native 0.70+
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enable Flipper (unless `NO_FLIPPER` is set)
    :flipper_configuration => flipper_config,
    # Absolute path to the root of the application
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ElewaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post install configuration (important for M1 Mac and Xcode 12.5+)
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
